### ISSUE TITLE
Unable to use with higher level API

### ISSUE THREAD

**Issue by Vikramank** [riga/tfdeploy#16] opened 2016-10-05 10:44 UTC
Hi, 
I am using tflearn, a higher level API like tfdeploy. I am unable to save my model

**Comment by riga** [comment] 2016-10-05 21:14
Hi,

can you provide an quick example showing the way to tried to save your model?
At the moment, tfdeploy is only able to store/convert real tensorflow tensor instances. It might be possible to extract the final tensor from higher-level API objects. I haven't looked into tflearn too much, so your example could actually help here.

**Comment by Vikramank** [comment] 2016-10-06 12:45
Hi, 
The code I am trying to save is the following one. 
(https://github.com/Vikramank/Deep-Learning-/blob/master/MNIST%20Classification.ipynb)
I have also listed the list of operations I've carried out for convenience. At the end, I wrote the following lines which threw me an error.  As you can see from the list operations, it contains standard TF operations only. It would be super awesome to use tfdeploy+tflearn

```
import tfdeploy as td
model = td.Model()
model.add(y, sess) 
model.save("model.pkl") 
```

**Comment by riga** [comment] 2016-10-07 14:45
tfdeploy does not support convolutions yet, but this will definitely come in the near future. Can you paste the stacktrace of the exception here?

**Comment by Vikramank** [comment] 2016-10-07 15:10
That's great. Looking forward it ! What do you mean by "stack trace" ? do you mean the output error?

**Comment by riga** [comment] 2016-12-06 10:58
Duplicate of #3.

**Closed by riga** 2016-12-06 10:58 UTC
Labels: duplicate
